os: linux
dist: trusty

services:
- docker

language: shell

branches:
  only:
  - master

script:
  # Build X86 docker image
  - docker build -f ./x86/Dockerfile -t solidrhino/spotweb .

  # Build ARM docker image
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f ./arm/Dockerfile -t solidrhino/rpi-spotweb .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    docker tag solidrhino/spotweb solidrhino/spotweb:latest
    docker tag solidrhino/spotweb solidrhino/spotweb:$TRAVIS_BUILD_NUMBER
    docker push solidrhino/spotweb

    docker tag solidrhino/rpi-spotweb solidrhino/rpi-spotweb:latest
    docker tag solidrhino/rpi-spotweb solidrhino/rpi-spotweb:$TRAVIS_BUILD_NUMBER
    docker push solidrhino/rpi-spotweb
  fi
