version: '3.3'

services:
  spotweb:
    build:
      context: .
      dockerfile: ./arm/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - "mysql"
    restart: always
    
  mysql:
    image: "mariadb:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
    volumes:
      - spotweb-data:/var/lib/mysql

volumes:
  spotweb-data:
